### ISSUE TITLE
Creating the JSON

### ISSUE THREAD

**Issue by rsignell-usgs** [kylebarron/usgs-dem-mosaic#3]
@kylebarron , feeling dumb here, but I followed the steps on the readme.md (downloaded the spatial metadata, grabbed the xml files, ran the code to generate geotiff_13_files.txt)

But.. how do I generate the MosaicJSON ?

I'm interested in this because we have a shiny new ti-tiler running on our USGS AWS account:  https://titiler.usgs.gov , and it looks like it works with MosaicJSON!

**Comment by kylebarron** [comment]
this project was never finished

**Comment by rsignell-usgs** [comment]
Okay, so now I don't feel so dumb!
But you did create MosaicJSON for this data somehow,  did you not? 
If so, could I try it?

**Comment by rsignell-usgs** [comment]
Or is MosaicJSON kind of dead, replaced by STAC?

**Comment by kylebarron** [comment]
no I never created mosaicjson for this data. mosaicjson has some uses when you need something more lightweight than a full STAC database
